### ISSUE TITLE
Conditional branching?

### ISSUE THREAD

**Issue by toish** [iansawyerva/gapp#1]
I could see this being useful for npm scripts! Always been a pain because you either have to write everything on on one line, or include shell script(s) in your repo somewhere, so it'd be cool if you could emulate some BASH patterns using arguments to make npm scripts a little easier to read, something like

## if - then
```bash
gapp -if $NODE_ENV -eq 'production'
     -then -r 'echo "Do something for production building here"'
```

## if - then - else
```bash
gapp -if $NODE_ENV -eq 'production'
     -then -r 'echo "Do something for production building here"'
     -else  -r 'echo "Start a dev server"'
```

You could chain `-if`, `-else`, and `-elseif` together to make some pretty complex but readable NPM scripts.

**Comment by iansawyerva** [comment]
Sounds like a great idea. I'm going to work on it now! You should definitely star and watch this repo! :x

**Comment by toish** [comment]
Awesome! I'm good to make a pull request too if ya want
